name: Merge master -> develop on push to master
on:
  push:
    branches:
      - 'master'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ github.token }
